### PR TITLE
Fix availability zone selection

### LINKED ISSUE #1700: Flakiness in vpc route table integration
```
insert or update on table "subnet" violates foreign key constraint "FK_89d16ba5682889f8fae7927052c"
```
https://github.com/iasql/iasql-engine/actions/runs/3743011942/jobs/6354724278

The problem is that the test is assuming that every region will have an availability zone with the pattern `<region>a`

### PR DESCRIPTION
**Pull request by aguillenv**
Resolves #1700

### CODE REVIEW

File: test/modules/aws-vpc-routetable-integration.ts [hunk 1]
```diff
@@ -135,7 +135,7 @@ describe('RouteTable Integration Testing', () => {
     query(
       `
       INSERT INTO subnet (availability_zone, vpc_id, cidr_block, region)
-      SELECT '${region}a', id, '10.${randIPBlock}.1.0/24', '${region}'
+      SELECT (SELECT name FROM availability_zone WHERE region = '${region}' ORDER BY 1 DESC LIMIT 1), id, '10.${randIPBlock}.1.0/24', '${region}'
```
Comment (dfellis) [inline test/modules/aws-vpc-routetable-integration.ts:138]: `Order by 1`?

Comment (aguillenv) [reply test/modules/aws-vpc-routetable-integration.ts:138]: It will order by the first column that is being returned. In this case, would be equivalent to:
```suggestion
      SELECT (SELECT name FROM availability_zone WHERE region = '${region}' ORDER BY name DESC LIMIT 1), id, '10.${randIPBlock}.1.0/24', '${region}'
```

Comment (dfellis) [reply test/modules/aws-vpc-routetable-integration.ts:138]: Wtfsql 😅

**Review by dfellis — APPROVED** [review]

File: test/modules/aws-vpc-routetable-integration.ts (hunk 1 above)
Comment (mtp1376) [reply test/modules/aws-vpc-routetable-integration.ts:138]: That pattern is used a lot in SQL injection because we don't know the column names :))
