### PR TITLE
Fix subnets from default vpc getting deleted

### LINKED ISSUE #671: Default subnets getting deleted when running clean script

### PR DESCRIPTION
**Pull request by aguillenv**
Resolves #671 

A race condition is occurring when checking the memo. It is being checked while a placeholder is in place so a empty object is being assigned.

What it should happen always:
`info vpc db object undefined`

What it is happening sometimes:
`info vpc db object {}`

### CODE REVIEW

File: src/modules/interfaces.ts [hunk 1]
```diff
@@ -147,6 +147,11 @@ export class Crud<E> {
           logger.info(`Cache miss for ${this.entity?.name ?? ''} ${this.dest}`);
           ctx.memo[dest][entityName][id] = new (this.entity as new () => E)();
         } else {
+          // If object is empty it means it is a placeholder and it is not in the memo yet.
+          if (!Object.keys(ctx.memo[dest][entityName][id]).length) {
+            logger.info(`Cache miss for ${this.entity?.name ?? ''} ${this.dest}`);
+            return undefined;
+          }
```
Comment (dfellis) [inline src/modules/interfaces.ts:154]: If this is staying in, should we just drop the placeholder logic? They aren't "getting through" to the users so they're just excessive complexity at this point?

**Review by dfellis — APPROVED** [review]

File: src/modules/interfaces.ts (hunk 1 above)
Comment (aguillenv) [reply src/modules/interfaces.ts:154]: I'll create a follow up task with this and try to tackle in a new PR.

**Review by depombo — APPROVED** [review]
