### PR TITLE
Manually close transaction if pg_cron commit failed

### LINKED ISSUE #1667: Transaction remains open if pg_cron commit fails

### PR DESCRIPTION
**Pull request by aguillenv**
Closes #1667

### CODE REVIEW

File: src/modules/iasql_functions/sql/after_install.sql [hunk 1]
```diff
@@ -114,7 +114,13 @@ begin
     -- If a transaction occurred less than 2 min ago we skip
     IF _change_type != 'OPEN_TRANSACTION' AND (_ts IS NULL OR _ts < _almost_2_min_interval) THEN
       PERFORM iasql_begin();
-      PERFORM iasql_commit();
+      BEGIN
+        PERFORM iasql_commit();
+      EXCEPTION
```
Comment (depombo) [inline src/modules/iasql_functions/sql/after_install.sql:119]: should we register the error as another log?

Comment (aguillenv) [reply src/modules/iasql_functions/sql/after_install.sql:119]: the TS function for iasql_commit would be already catching errors and inserting the error log once this is landed https://github.com/iasql/iasql-engine/pull/1663

**Review by depombo — APPROVED** [review]

**Review by dfellis — APPROVED** [review]
