### PR TITLE
`aws_security_group` flakiness fix

### LINKED ISSUE #566: aws_security_group flakiness
The security group module is showing signs of flakiness. Misidentifying records from the cloud as being different from a record in the database and then failing due to uniqueness constraints when they are actually "the same" from the database's perspective.

Figuring out why this is happening and turning the `db.create` into a `db.update` call when this happens should fix it.

### PR DESCRIPTION
**Pull request by dfellis**
Resolves #566

### CODE REVIEW

File: src/services/iasql.ts [hunk 1]
```diff
@@ -365,6 +365,7 @@ export async function apply(dbId: string, dryRun: boolean, ormOpt?: TypeormWrapp
         }
         records.forEach(r => {
           r.diff = findDiff(r.dbEntity, r.cloudEntity, r.idGen, r.comparator);
+          if (['SecurityGroup', 'SecurityGroupRule'].includes(r.table)) console.log(r.diff);
```
Comment (dfellis) [inline src/services/iasql.ts:368]:
```suggestion
```

**Comment by dfellis** [comment]
Pretty sure that test failure is due to contention issues (we only made it less likely to collide, not impossible)

**Review by aguillenv — APPROVED** [review]

**Review by depombo — APPROVED** [review]
